name: ShiftLeft NGSAST with BOM generation

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Download ShiftLeft cli
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build with Maven
      run: ${GITHUB_WORKSPACE}/sl bom generate --java
    - name: ShiftLeft Analyze
      run:  ${GITHUB_WORKSPACE}/sl analyze --wait --sca --bomupload bom.xml --java --app jvl-bom-sca --force --cpg target/JavaVulnerableLab.war
    env:
      SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
